### ISSUE TITLE
Handle Timeouts

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/python-zbMathRest2Oai#82]
**Describe the bug**
root@44ebd050cc0c:/python-zbMathRest2Oai# cat err.log 
Traceback (most recent call last):
  File "/python-zbMathRest2Oai/src/zbmath_rest2oai/run_get_all_de_documents.py", line 3, in <module>
    get_all(
  File "/python-zbMathRest2Oai/src/zbmath_rest2oai/get_all.py", line 9, in get_all
    res = write_oai(api_source=uri_request, prefix=prefix, ingest_format=ingest_format)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/python-zbMathRest2Oai/src/zbmath_rest2oai/writeOai.py", line 50, in write_oai
    records, last_id = asyncio.run(async_write_oai(test_xml, ingest_format))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/python-zbMathRest2Oai/src/zbmath_rest2oai/writeOai.py", line 42, in async_write_oai
    await asyncio.gather(*tasks)
  File "/python-zbMathRest2Oai/src/zbmath_rest2oai/writeOai.py", line 17, in post_item
    async with session.post(URL, data=files, auth=AUTH) as response:
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 1197, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 608, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 971, in start
    with self._timer:
  File "/usr/local/lib/python3.12/site-packages/aiohttp/helpers.py", line 735, in __exit__
    raise asyncio.TimeoutError from None
TimeoutError
root@44ebd050cc0c:/python-zbMathRest2Oai# cat state.json 
{
    "software": 0,
    "document": 7731222,
    "document_perf": {
        "records": 4621500,
        "time_rest": 62472.722091000214,
        "time_oai": 23321.4644440189
    }
}root@44ebd050cc0c:/python-zbMathRest2Oai# 

**Checklist for this issue**: 
(Some checks for making sure this issue is completely formulated)
- [x] Assignee has been set for this issue 
- [x] All fields of the issue have been filled 
- [ ] the main MaRDI project has been assigned as project

**Comment by Mazztok45** [comment]
This commit fixed the issues with time out:
https://github.com/MaRDI4NFDI/python-zbMathRest2Oai/commit/b03b11fd29956b3b0a955a664b2643e41a2e749c
